let produtos = [
{
        titulo : "Kit primeiros socorros",
        descricao : "Essencial para situações de emergência. Contém materiais para controle de hemorragias, tratamento de ferimentos e imobilização. Pronto para uso em qualquer missão",
        link : "https://shopee.com.br/kit-de-Primeiros-Socorros-Com-bolsa-i.329150782.15318888409",
        video : "https://www.youtube.com/shorts/usb7yC3V754",
        valor : "R$120,00",
    },
{
        titulo : "Kit de sobrevivencia",
        descricao : "Completo com bússola, isqueiro à prova d'água, corda de sobrevivência e ferramentas multifuncionais. Perfeito para aventuras em ambientes hostis.",
        link : "#",
        video : "https://www.youtube.com/shorts/frr3oti75GE",
        valor : "R$130,00",
    },
{
        titulo : "Kit de anotação",
        descricao : "Inclui bloco de notas resistente à água, caneta de sobrevivência tática e estojo impermeável. Ideal para missões em qualquer condição climática.",
        link : "#",
        video : "#",
        valor : "R$99,00",
    },
{
        titulo : "Kit de campanha militar",
        descricao : "Composto por barraca portátil, saco de dormir térmico e utensílios de cozinha leves. Perfeito para missões longas e em campo.",
        link : "#",
        video : "#",
        valor : "R$250,00",
    },
    {
        titulo: "Faca tática",
        descricao: "Faca de alta qualidade para uso militar, com lâmina em aço inoxidável e cabo ergonômico.",
        link: "https://www.exemplo.com/faca-tatica",
        video: "https://www.youtube.com/watch?v=seuVideo1",
        material: "Aço inoxidável",
        valor : "R$160,00",
      },
      {
        titulo: "Binóculo militar",
        descricao: "Binóculo de alta potência com zoom ajustável, ideal para uso em campo.",
        link: "https://www.exemplo.com/binoculo-militar",
        video: "https://www.youtube.com/watch?v=seuVideo2",
        valor : "R$100,00",
      },
      {
        titulo: "Mochila tática",
        descricao: "Mochila resistente e modular, ideal para carregar equipamentos militares.",
        link: "https://www.exemplo.com/mochila-tatica",
        video: "https://www.youtube.com/watch?v=seuVideo3",
        valor : "R$200,00",
      },
      {
        titulo: "Óculos de proteção balísticos",
        descricao: "Óculos de proteção balística com lentes resistentes a impactos e raios UV.",
        link: "https://www.exemplo.com/oculos-balisticos",
        video: "https://www.youtube.com/watch?v=seuVideo4",
        valor : "R$20,00",
      },
      {
        titulo: "GPS militar",
        descricao: "GPS portátil com alta precisão e resistente à água.",
        link: "https://www.exemplo.com/gps-militar",
        video: "https://www.youtube.com/watch?v=seuVideo5",
        valor : "R$500,00",
      },
      {
        titulo: "Cantil militar",
        descricao: "Cantil de alumínio resistente e durável, ideal para transportar água.",
        link: "https://www.exemplo.com/cantil-militar",
        video: "https://www.youtube.com/watch/v=seuVideo7",
        capacidade: "1L",
        valor : "R$15,00",
      },
      {
        titulo: "Bússola militar",
        descricao: "Bússola de alta precisão para orientação em campo.",
        link: "https://www.exemplo.com/bussola-militar",
        video: "https://www.youtube.com/watch?v=seuVideo8",
        valor : "R$50,00",
      },
      {
        titulo: "Luva tática",
        descricao: "Luva tática resistente e com boa aderência, ideal para manusear armas.",
        link: "https://www.exemplo.com/luva-tatica",
        video: "https://www.youtube.com/watch/v=seuVideo9",
        material: "Kevlar",
        valor : "R$60,00",
      },
      {
        titulo: "Bastão retrátil",
        descricao: "Bastão retrátil de defesa pessoal, leve e fácil de transportar.",
        link: "https://www.exemplo.com/bastao-retratil",
        video: "https://www.youtube.com/watch/v=seuVideo10",
        valor : "R$135,00",
      }
    ];
